
PROG = main
CFLAGS = -Wall -Wextra -g -c -O2
CC = g++
OBJS = 

$(PROG): $(OBJS)
		$(CC)  -o $(PROG) $(OBJS)

.PHONY: all
all:$(PROG)

.o:.cpp 
		$(CC) $(CFLAGS) m.cpp

.PHONY: clean
	clean:
		rm -f $(PROG) $(OBJS)
